  1 
  2 # prefix override
  3 set -g prefix C-l
  4 
  5 # Switch to the previous window using Alt + Left Arrow
  6 bind-key -n M-Left previous-window
  7 
  8 # Switch to the next window using Alt + Right Arrow
  9 bind-key -n M-Right next-window
 10 
 11 # Press Alt + N to terminate current window 
 12 bind-key -n M-N kill-window
 13 # Press Alt + n to prompt for a new window 
 14 bind-key -n M-n new-window
