# status bar
set -g status-right-length 80
set -g status-right '[#(tmux ls -F "##S##{?session_attached,*,}" | tr "\n" " " | sed "s/ $//" )]'

# prefix override
set -g prefix C-l

# Switch to the previous session using Alt + Left Arrow
bind-key -n M-Left switch-client -p

# Switch to the next session using Alt + Right Arrow
bind-key -n M-Right switch-client -n

# Press Alt + N to prompt for a new session 
bind-key -n M-n new-session 
